### ISSUE TITLE
500 Error When Using Comment Removal Process

### ISSUE THREAD

**Issue by skilfullycurled** [yourcelf/btb#35]
Blogger requested that two comments be removed per this [letter](https://betweenthebars.org/moderation/#/process/document/25242):

Removed comments using [standard removal method](https://betweenthebars.org/comments/comment/13306/moderator_remove):

Steps to recreate:

1. Created reason in [admin backend](https://betweenthebars.org/admin/comments/removalreason/)
2. Reason: "Request From Blogger"
3. Web message: blank
4. Comment author message: blank (no email address for comment author)
5. Post author message: "Per your request in a letter dated 6/12/17, we have removed the following comment."
6. Preview rendered letter (Throws 500)
7. Remove comment and send notification (Throws 500)

**Comment by yourcelf** [comment]
Fixed in e58e3741bbf14f9d85818890a0c80cc6aa33cc0e.  The script that escapes input for Latex rendering was not properly converting windows-style CRLF line endings (e.g. `"\r\n"`) into latex-style newlines (e.g. `"\\"`).   It only replaced the LF part (`"\n"`), leaving the string `"\r\\"` in the latex document, which caused an error.  It appears that bare CRLF endings in the comment body triggered this.  Windows-style line endings are now properly escaped.
